### ISSUE TITLE
How to handle rate limiting?

### ISSUE THREAD

**Issue by cmeans** [resilient-http/resilient.js#128]
Sorry, I couldn't find a place to get support/help.

I'm calling an API via Resilient that has rate limiting.  Is there a standard way to have the Resilient client resend a request that was previously subject to rate limiting?

In this case, the response includes a header that indicates the rate limiting was hit, so I'd just like to be able to "automatically" resubmit the request should I get back that specific header/value.

**Comment by h2non** [comment]
Resilient is treating `429` status codes as failed request. The API you're using is responding with that status?

Ideally, you should plug in your own strategies to evaluate if a request was failed or not, but unfortunately this is not yet supported.

**Comment by cmeans** [comment]
No, unfortunately, the API I'm using returns 200.

**Comment by h2non** [comment]
I think I can do something to cover that need... I'll let you know.

**Comment by cmeans** [comment]
Thanks.  No rush, I've implemented a work-around that appears to be working
for the moment.

**Comment by h2non** [comment]
You got it! I've just supported it, and I believe that the versatility of the feature should cover all your current and potentially future needs.

Take a look to the [docs](https://github.com/resilient-http/resilient.js#resilientaddfailstrategystrategy), the [test](https://github.com/resilient-http/resilient.js/blob/master/test/fail-strategies.js) I've wrote and the [example](https://github.com/resilient-http/resilient.js/blob/master/examples/custom-fail-strategies.js).

To he honest, I had in the roadmap features like for a while, so I'm glad to finally support it to help someone. With this feature, you can for instance plug in a set of strategies for different cases, like using this [module](https://github.com/h2non/is-fail).

Worth to say that I've just released a fresh version, so feel free to update via `npm` or `bower`.

**Comment by cmeans** [comment]
Fantastic.  Thanks!

**Comment by cmeans** [comment]
Possibly, I've not implemented the pattern correctly, but the callback for
the request that failed is still being called, and without the "status"
property being present.

**Comment by cmeans** [comment]
The status property of the response object.

**Comment by h2non** [comment]
Only two params are passed to the strategy function: `Error` and [`http.IncomingMessage`](https://nodejs.org/api/http.html#http_http_incomingmessage). 
Note that Resilient uses the raw node.js `http` module API, so you have to check the `statusCode` property.

Just to clarify, if `Error` is present, the second argument is `undefined`. If `http.IncomingMessage` is present, error is `null`.

**Comment by cmeans** [comment]
I'm referring to the callback of the client.get call.  But I believe I
understand now.  Thanks.

**Comment by h2non** [comment]
That's the same, the interface is exactly equal.

**Comment by cmeans** [comment]
Should the callback from the client.get call still be called if there's a
Rate Limit "failure"?

I had assumed that Resilient would automatically retry (options.retry
times) before actually failing.

**Comment by h2non** [comment]
It depends on your specific configuration, but generally yes: when the max amount of retries exceeds and the error status remains across all the attempts, the request callback will be called with an error status.

**Comment by cmeans** [comment]
My mistake, I was not configuring Resilient correctly (I'd missed the extra
level of braces necessary for the config object).  All good.

**Comment by h2non** [comment]
Excellent, no worries!
